# Generated by Django 5.1.2 on 2024-12-26 12:44

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100, unique=True)),
                ('Category', models.CharField(choices=[('TECH', 'TECH'), ('ENTERTAINMENT', 'ENTERTAINMENT'), ('FINANCE', 'FINANCE')], default='TECH', max_length=50)),
                ('Sub_category', models.CharField(blank=True, max_length=100, null=True)),
                ('Date_published', models.DateField(auto_now_add=True)),
                ('Views', models.IntegerField(default=0)),
                ('Content', models.TextField(default='hello')),
                ('Labels', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('FEATURED', 'FEATURED'), ('BREAKING NEWS', 'BREAKING NEWS'), ('TRENDING', 'TRENDING'), ('HAPPENING TODAY', 'HAPPENING TODAY'), ('TOP TODAY', 'TOP TODAY')], max_length=57, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commenter_name', models.CharField(max_length=30, null=True, unique=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('comment', models.TextField(null=True)),
                ('related_article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.article')),
            ],
        ),
    ]
