# Generated by Django 5.1.2 on 2024-12-26 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='Sub_category',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
