# Generated by Django 5.1.3 on 2024-11-23 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='structure',
            name='content',
        ),
        migrations.AddField(
            model_name='structure',
            name='categories',
            field=models.CharField(choices=[('tech', 'TECH'), ('entertainment', 'ENTERTAINMENT'), ('finance', 'FINANCE')], default='tech', max_length=20),
        ),
        migrations.AlterField(
            model_name='structure',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
