# Generated by Django 5.1.2 on 2024-12-28 10:47

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_article_sub_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='Sub_category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('TECH FOR GOOD', 'Tech: TECH FOR GOOD'), ('EMERGING TECH', 'Tech: EMERGING TECH'), ('CYBERSECURITY', 'Tech: CYBERSECURITY'), ('TECH EMPOWERMENT', 'Tech: TECH EMPOWERMENT')], max_length=58, null=True),
        ),
    ]
