# Generated by Django 5.1.3 on 2024-11-23 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_remove_structure_content_structure_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structure',
            name='categories',
            field=models.CharField(choices=[('tech', [('good', 'Good'), ('bad', 'Bad'), ('ugly', 'Ugly')]), ('entertainment', 'ENTERTAINMENT'), ('finance', 'FINANCE')], default='tech', max_length=20),
        ),
    ]
