# Generated by Django 5.1.2 on 2024-12-28 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_article_sub_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='Date_published',
            new_name='DatePublished',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='Sub_category',
            new_name='SubCategory',
        ),
    ]
