# Generated by Django 5.1.3 on 2024-11-23 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_structure_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='structure',
            old_name='title',
            new_name='Title',
        ),
        migrations.AddField(
            model_name='structure',
            name='Content',
            field=models.TextField(default='hello'),
        ),
        migrations.AddField(
            model_name='structure',
            name='Is_Featured',
            field=models.BooleanField(default=False),
        ),
    ]
