# Generated by Django 5.1.2 on 2024-12-28 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_rename_date_published_article_datepublished_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='Extra',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
