# Generated by Django 5.1.3 on 2024-11-24 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_rename_title_structure_title_structure_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='structure',
            name='categories',
        ),
        migrations.AddField(
            model_name='structure',
            name='Category',
            field=models.CharField(choices=[('TECH', [('TECH FOR GOOD', 'TECH FOR GOOD'), ('EMERGING TECH', 'EMERGING TECH'), ('HARDWARE & SOFTWARE', 'HARDWARE & SOFTWARE'), ('NETWORKING & SECURITY', 'NETWORKING & SECURITY'), ('TECH CAREER & CULTURE', 'TECH CAREER & CULTURE')]), ('ENTERTAINMENT', [('FASHION & LIFESTYLE', 'FASHION & LIFESTYLE'), ('SHOWBIZ & FILMDOM', 'SHOWBIZ & FILMDOM'), ('CELEBRITIES & GOSSIP', 'CELEBRITIES & GOSSIP'), ('AWARDS & EVENTS', 'AWARDS & EVENTS'), ('TRAILERS & SKITS', 'TRAILERS & SKITS')]), ('FINANCE', [('MARKET NEWS', 'MARKET NEWS'), ('INDUSTRY & ECONOMY', 'INDUSTRY & ECONOMY'), ('CRYPTOCURRENCY', 'CRYPTOCURRENCY')])], default='tech', max_length=50),
        ),
        migrations.AddField(
            model_name='structure',
            name='Is_HappeningToday',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='structure',
            name='Title',
            field=models.CharField(max_length=50),
        ),
    ]
