# Generated by Django 5.1.3 on 2024-11-24 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_remove_structure_categories_structure_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='structure',
            name='Is_HappeningToday',
        ),
        migrations.AlterField(
            model_name='structure',
            name='Is_Featured',
            field=models.CharField(choices=[('featured', models.BooleanField(null=True)), ('breaking', models.BooleanField(null=True))], max_length=50),
        ),
        migrations.AlterField(
            model_name='structure',
            name='Title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
