# Generated by Django 5.1.3 on 2024-11-24 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_remove_structure_is_happeningtoday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structure',
            name='Is_Featured',
            field=models.BooleanField(null=True),
        ),
    ]
