# Generated by Django 5.1.2 on 2024-12-28 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_remove_article_labels_article_breakingnews_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='BreakingNews',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='Featured',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='HappeningToday',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='TopToday',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='Trending',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
