# Generated by Django 5.1.3 on 2024-11-25 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_remove_structure_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='Is_Featured',
            field=models.BooleanField(choices=[('featured', 'featured'), ('lorem', 'lorem')], null=True),
        ),
    ]
