# Generated by Django 5.1.3 on 2024-11-25 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_alter_structure_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structure',
            name='Is_Featured',
            field=models.BooleanField(default=True),
        ),
    ]
