# Generated by Django 5.1.2 on 2024-12-29 20:10

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_remove_article_labels_article_breakingnews_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='BreakingNews',
        ),
        migrations.RemoveField(
            model_name='article',
            name='Featured',
        ),
        migrations.RemoveField(
            model_name='article',
            name='HappeningToday',
        ),
        migrations.RemoveField(
            model_name='article',
            name='SubCategory',
        ),
        migrations.RemoveField(
            model_name='article',
            name='TopToday',
        ),
        migrations.RemoveField(
            model_name='article',
            name='Trending',
        ),
        migrations.AddField(
            model_name='article',
            name='Labels',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('FEATURED', 'FEATURED'), ('BREAKING NEWS', 'BREAKING NEWS'), ('TRENDING', 'TRENDING'), ('HAPPENING TODAY', 'HAPPENING TODAY'), ('TOP TODAY', 'TOP TODAY')], max_length=57, null=True),
        ),
    ]
