# Generated by Django 5.1.2 on 2024-12-29 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_remove_article_breakingnews_remove_article_featured_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='Labels',
        ),
        migrations.AddField(
            model_name='article',
            name='BreakingNews',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='Featured',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='HappeningToday',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='TopToday',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='Trending',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
