# Generated by Django 5.1.3 on 2024-11-26 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_alter_structure_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structure',
            name='Category',
            field=models.CharField(choices=[('TECH', 'TECH'), ('ENTERTAINMENT', 'ENTERTAINMENT'), ('FINANCE', 'FINANCE')], default='TECH', max_length=50),
        ),
    ]
