# Generated by Django 5.1.3 on 2024-11-26 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_alter_structure_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Structure',
            new_name='Stories',
        ),
        migrations.AlterModelOptions(
            name='stories',
            options={'verbose_name': 'Stories.Title'},
        ),
    ]
