# Generated by Django 5.1.3 on 2024-11-26 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_rename_structure_stories_alter_stories_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stories',
            options={},
        ),
    ]
