# Generated by Django 5.1.3 on 2024-11-26 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_alter_stories_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='stories',
            table='Stories.Title',
        ),
    ]
