# Generated by Django 5.1.3 on 2024-11-26 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_alter_stories_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stories',
            new_name='Article',
        ),
    ]
