# Generated by Django 5.1.3 on 2024-11-26 12:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='Date_published',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='article',
            table=None,
        ),
    ]
