# Generated by Django 5.1.3 on 2024-12-07 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0019_rename_date_published_article_date_publishd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='commenter_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='comments',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='comments',
            name='related_article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.article'),
        ),
        migrations.AlterField(
            model_name='article',
            name='Is_Featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
