# Generated by Django 5.1.3 on 2024-12-07 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0020_comments_commenter_name_comments_email_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
