# Generated by Django 5.1.3 on 2024-12-07 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0022_rename_date_publishd_article_date_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='Title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
